# Stage 1: Development
FROM node:22 AS development

WORKDIR /usr/src/app

# Install Angular CLI globally
RUN npm install -g @angular/cli@latest

# Copy package.json and package-lock.json first for better caching
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Set environment variable
ENV NODE_ENV=development

# Expose Angular's default development port
EXPOSE 4200

# Serve the Angular app
CMD ["node", "--max-old-space-size=2048", "node_modules/@angular/cli/bin/ng", "serve", "--host", "0.0.0.0", "--poll=2000"]

