import jwt from "jsonwebtoken";
import { ReactNode } from "react";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

import type { Metadata } from "next";
import RootProvider from "@/components/providers/root-provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
const Layout = async ({ children }: { children: ReactNode }) => {
	const cookieStore = await cookies();
	const accessToken = cookieStore.get("accessToken")?.value;
	// const refreshToken = cookieStore.get("refreshToken")?.value;

	// if (!accessToken) {
	// 	redirect("/auth/login");
	// }

	// const tokenValue = jwt.verify(
	// 	accessToken,
	// 	process.env.NEXT_JWT_SECRET as string
	// ) as {
	// 	userId: string;
	// 	username?: string;
	// };

	// if (!tokenValue?.userId) {
	// 	redirect("/auth/login");
	// }
	return <>{children}</>;
};

export default Layout;
