FROM node:20 AS development
WORKDIR /usr/src/app
RUN npm install -g @nestjs/cli nodemon
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npx", "nodemon", "--watch", "src", "--exec", "npm run start:dev"]
