# Stage 1: Development
FROM node:18 AS development

WORKDIR /usr/src/app

# Install Nest CLI
RUN npm install -g @nestjs/cli

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY . .

# Expose the API port
EXPOSE 3000

# Start the NestJS app in watch mode
CMD ["npm", "run", "start:dev"]
